@startuml
actor resident
node rollershutter_openhab
node mqtt
node jiottranslate
node mixing_valve

resident --> rollershutter_openhab
rollershutter_openhab --> mqtt
mqtt <--> jiottranslate
mqtt ->rollershutter_controller

@enduml
